---
title: "Using ccc_plots and ggplot2 for publication graphics"
author: "John Ehrlinger"
date: "August 29, 2014"
output: html_document
---


```sas
data green_j; set green; keep iv_state sginit stlinit stuinit
sgdead1 stldead1 studead1
sgstrk1 stlstrk1 stustrk1;

libname out xport "&STUDY/datasets/npar_cst.xpt";
data out.npar_cst;
set green_j;
run;


data all_j; set all;  keep years   noinit clinit cuinit 
nodeath cldeath cudeath 
nostrk clstrk custrk  ;

libname out xport "&STUDY/datasets/par_cst.xpt";
data out.par_cst;
set all;
run;

*******************************************************************************;
* Bring in PostScript plot macro                                               ;
filename plt "!MACROS/plot.sas"; %inc plt;
filename gsasfile pipe 'lp';
*______________________________________________________________________________;
*                                                                              ;
*                       P O S T S C R I P   P L O T S
*______________________________________________________________________________;
*                                                                              ;
* Multiple decrement, nonparametric and parametric                             ;
filename gsasfile "&STUDY/graphs/ce.states.ST_toJohn.both.ps";
%plot(goptions gsfmode=replace, device=pscolor, gaccess=gsasfile end;
id l="&STUDY/graphs/ce.states.ST_toJohn.sas percent", end;
labelx l="Years After Randomization", end;
axisx order=(0 to 5 by 1), minor=none, end;
labely l="Percent in Each Category (ST)", end;
axisy order=(0 to 100 by 10), minor=none, end;


/******NON-PARAMETRIC: SYMBOLS AND CONFIDENCE BARS *******/
tuple set=green, symbol=dot, symbsize=1/2, linepe=0, linecl=0,
ebarsize=3/4, ebar=1,
x=iv_state, y=sginit, cll=stlinit, clu=stuinit, color=black, end;
tuple set=green, symbol=circle, symbsize=1/2, linepe=0, linecl=0,
ebarsize=3/4, ebar=1,
x=iv_state, y=sgdead1, cll=stldead1, clu=studead1, color=blue, end;
tuple set=green, symbol=square, symbsize=1/2, linepe=0, linecl=0,
ebarsize=3/4, ebar=1,
x=iv_state, y=sgstrk1, cll=stlstrk1, clu=stustrk1, color=blue, end;


/**********PARAMETRIC : SOLID LINES AND CONFIDENCE INTERVALS**********/      
tuple set=all, x=years, y=noinit, cll=clinit, clu=cuinit,
width=0.5,color=black, end;

tuple set=all, x=years, y=nodeath, cll=cldeath, clu=cudeath,
width=0.5,color=blue, end;

tuple set=all, x=years, y=nostrk, cll=clstrk, clu=custrk,
linecl=2, width=0.5,color=blue, end;
);
run;
*******************************************************************************;

*______________________________________________________________________________;
*                                                                              ;
*       C G M   F I L E S   F O R   P O W E R P O I N T   S L I D E S
*______________________________________________________________________________;
*                                                                              ;
* Competing risks, parametric only                                             ;
filename gsasfile "&STUDY/graphs/ce.states.ST_toJohn.cgm";
%plot(goptions gsfmode=replace, device=cgmmppa, ftext=hwcgm001, end;
axisx order=(0 to 5 by 1), minor=none, value=(height=2.4), end;
axisy order=(0 to 100 by 20), minor=none, value=(height=2.4), 
value=(height=2.4 j=r ' ' '20' '40' '60' '80' '100'), end;
tuple set=all, x=years, y=noinit, width=3, color=gray, end;
tuple set=all, x=years, y=nostrk, width=3, color=red, end;
tuple set=all, x=years, y=nodeath, width=3, color=blue, end;
);
run;  

```
```{r read_data}
library(knitr)
load("../data/parametric.rda")

load("../data/nonparametric.rda")

library(ggplot2)
library(dplyr)
```
You can also embed plots, for example:

```{r, echo=FALSE}
## To reproduce the plot.sas function, line by line.
###-------------
## There are SAS options we will not use here.
#
#  %plot(goptions gsfmode=replace, device=pscolor, gaccess=gsasfile end;
ccf_plot <- ggplot()

#    id l="&STUDY/graphs/ce.states.ST_toJohn.sas percent", end;

###-------------
## Labels are a single command, scales control the axis
#
#    labelx l="Years After Randomization", end;
#      axisx order=(0 to 5 by 1), minor=none, end;
#    labely l="Percent in Each Category (ST)", end;
#      axisy order=(0 to 100 by 10), minor=none, end;
ccf_plot <- ccf_plot +
  labs(x="Years After Randomization",
       y="Percent in Each Category (ST)")+
  scale_x_continuous(breaks=seq(0,5,1))+
  scale_y_continuous(breaks=seq(0,100,10))


###-------------
## /******NON-PARAMETRIC: SYMBOLS AND CONFIDENCE BARS *******/
##
## Each tuple statement corresponds to one or more geom_ statements
#     tuple set=green, symbol=dot, symbsize=1/2, linepe=0, linecl=0,
#       ebarsize=3/4, ebar=1,
#       x=iv_state, y=sginit, cll=stlinit, clu=stuinit, color=black, end;

ccf_plot <- ccf_plot +
  geom_point(data=nonparametric, aes(x=iv_state, y=sginit))

#     tuple set=green, symbol=circle, symbsize=1/2, linepe=0, linecl=0,
#       ebarsize=3/4, ebar=1,
#       x=iv_state, y=sgdead1, cll=stldead1, clu=studead1, color=blue, end;
ccf_plot <- ccf_plot +
  geom_point(data=nonparametric, aes(x=iv_state, y=sgdead1),color="blue",shape=1) + 
  geom_errorbar(data=nonparametric, aes(x=iv_state, ymin=stldead1, ymax=studead1), color="blue", width=.1)

#      tuple set=green, symbol=square, symbsize=1/2, linepe=0, linecl=0,
#       ebarsize=3/4, ebar=1,
#       x=iv_state, y=sgstrk1, cll=stlstrk1, clu=stustrk1, color=blue, end;
ccf_plot <- ccf_plot +
  geom_point(data=nonparametric, aes(x=iv_state, y=sgstrk1),color="blue",shape=0) + 
  geom_errorbar(data=nonparametric, aes(x=iv_state, ymin=stlstrk1, ymax=stustrk1), color="blue", width=.1)

ccf_plot
```


```{r parametric}

# /**********PARAMETRIC : SOLID LINES AND CONFIDENCE INTERVALS**********/      
# tuple set=all, x=years, y=noinit, cll=clinit, clu=cuinit,
# width=0.5,color=black, end;

ccf_plot <- ccf_plot+
  geom_line(data=parametric, aes(x=years, y=noinit))+
  geom_line(data=parametric, aes(x=years, y=clinit), linetype="dashed")+
  geom_line(data=parametric, aes(x=years, y=cuinit), linetype="dashed")
# 
# tuple set=all, x=years, y=nodeath, cll=cldeath, clu=cudeath,
# width=0.5,color=blue, end;
ccf_plot <- ccf_plot+
  geom_line(data=parametric, aes(x=years, y=nodeath), color="blue")+
  geom_line(data=parametric, aes(x=years, y=cldeath), linetype="dashed", color="blue")+
  geom_line(data=parametric, aes(x=years, y=cudeath), linetype="dashed", color="blue")
# 
# tuple set=all, x=years, y=nostrk, cll=clstrk, clu=custrk,
# linecl=2, width=0.5,color=blue, end;
ccf_plot <- ccf_plot+
  geom_line(data=parametric, aes(x=years, y=nostrk), color="blue")+
  geom_line(data=parametric, aes(x=years, y=clstrk), linetype="dashed", color="blue")+
  geom_line(data=parametric, aes(x=years, y=custrk), linetype="dashed", color="blue")

ccf_plot
```
