# Package-wide constants

HVTI_SCORE_MIN <- 0
HVTI_SCORE_MAX <- 100
HVTI_SCORE_BREAK_STEP <- 10
HVTI_SCORE_MARGIN_RATIO <- 0.10
HVTI_SCORE_FILL_RATIO <- 0.95
HVTI_SCORE_DEFAULT_MULTIPLIER <- 100
HVTI_ANNOTATION_X <- 20
HVTI_MATCH_PROBABILITY <- 0.6

HVTI_THEME_PPT_BASE_SIZE <- 32
HVTI_THEME_DARK_PPT_BASE_SIZE <- 32
HVTI_THEME_POSTER_BASE_SIZE <- 16
HVTI_THEME_MANUSCRIPT_MARGIN <- c(0.65, 0.65, 0.25, 0.25)
HVTI_THEME_POSTER_AXIS_TEXT_SIZE <- 16
